name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to github registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch lego release version
        id: lego_ver
        run: |
          echo "version=$(curl -sL https://api.github.com/repos/go-acme/lego/releases/latest | jq -r '.tag_name')" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: VERSION=${{ steps.lego_ver.outputs.version }}
          push: true
          tags: |
            ghcr.io/icefo/acme-lego-cron:latest
            ghcr.io/icefo/acme-lego-cron:${{ steps.lego_ver.outputs.version }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/icefo/acme-lego-cron
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
